[package]
name = "ceresdb"
version = "1.2.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[workspace.package]
version = "1.2.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[workspace]
# In alphabetical order
members = [
    "analytic_engine",
    "benchmarks",
    "catalog",
    "catalog_impls",
    "cluster",
    "common_types",
    "common_util",
    "components/arena",
    "components/arrow_ext",
    "components/bytes_ext",
    "components/logger",
    "components/message_queue",
    "components/object_store",
    "components/parquet_ext",
    "components/profile",
    "components/skiplist",
    "components/table_kv",
    "components/trace_metric",
    "components/trace_metric_derive",
    "components/trace_metric_derive_tests",
    "components/tracing_util",
    "df_operator",
    "integration_tests",
    "integration_tests/sdk/rust",
    "interpreters",
    "meta_client",
    "partition_table_engine",
    "proxy",
    "query_engine",
    "query_frontend",
    "remote_engine_client",
    "router",
    "server",
    "system_catalog",
    "table_engine",
    "tools",
    "wal",
]

[[bin]]
name = "ceresdb-server"
path = "src/bin/ceresdb-server.rs"

[workspace.dependencies]
arrow = { version = "38.0.0", features = ["prettyprint"] }
arrow_ipc = { version = "38.0.0" }
arrow_ext = { path = "components/arrow_ext" }
analytic_engine = { path = "analytic_engine" }
arena = { path = "components/arena" }
async-stream = "0.3.4"
async-trait = "0.1.53"
base64 = "0.13"
bytes = "1.1.0"
bytes_ext = { path = "components/bytes_ext" }
catalog = { path = "catalog" }
catalog_impls = { path = "catalog_impls" }
ceresdbproto = "1.0.4"
chrono = "0.4"
clap = "3.0"
clru = "0.6.1"
cluster = { path = "cluster" }
criterion = "0.3"
common_types = { path = "common_types" }
common_util = { path = "common_util" }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", rev = "06e9f53637f20dd91bef43b74942ec36c38c22d5" }
datafusion-proto = { git = "https://github.com/apache/arrow-datafusion.git", rev = "06e9f53637f20dd91bef43b74942ec36c38c22d5" }
df_operator = { path = "df_operator" }
etcd-client = "0.10.3"
env_logger = "0.6"
futures = "0.3"
xorfilter-rs = { git = "https://github.com/datafuse-extras/xorfilter", tag = "databend-alpha.4" }
lazy_static = "1.4.0"
log = "0.4"
logger = { path = "components/logger" }
lru = "0.7.6"
influxql-logical-planner = { git = "https://github.com/CeresDB/influxql", package = "iox_query_influxql" }
influxql-parser = { git = "https://github.com/CeresDB/influxql", package = "influxdb_influxql_parser" }
influxql-query = { git = "https://github.com/CeresDB/influxql", package = "iox_query" }
influxql-schema = { git = "https://github.com/CeresDB/influxql", package = "schema" }
interpreters = { path = "interpreters" }
itertools = "0.10.5"
meta_client = { path = "meta_client" }
object_store = { path = "components/object_store" }
partition_table_engine = { path = "partition_table_engine" }
parquet_ext = { path = "components/parquet_ext" }
parquet = { version = "38.0.0" }
paste = "1.0"
pin-project-lite = "0.2.8"
profile = { path = "components/profile" }
prom-remote-api = { version = "0.2.2" }
prometheus = "0.12"
prometheus-static-metric = "0.5"
prost = "0.11"
proxy = { path = "proxy" }
query_engine = { path = "query_engine" }
rand = "0.7"
remote_engine_client = { path = "remote_engine_client" }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
router = { path = "router" }
snafu = { version = "0.6.10", features = ["backtraces"] }
serde = "1.0"
serde_json = "1.0.60"
server = { path = "server" }
smallvec = "1.6"
slog = "2.7"
spin = "0.9.6"
query_frontend = { path = "query_frontend" }
sqlparser = { version = "0.33", features = ["serde"] }
system_catalog = { path = "system_catalog" }
table_engine = { path = "table_engine" }
table_kv = { path = "components/table_kv" }
tempfile = "3.1.0"
toml = "0.7"
tracing_util = { path = "components/tracing_util" }
trace_metric = { path = "components/trace_metric" }
trace_metric_derive = { path = "components/trace_metric_derive" }
trace_metric_derive_tests = { path = "components/trace_metric_derive_tests" }
tonic = "0.8.1"
tokio = { version = "1.25", features = ["full"] }
wal = { path = "wal" }
message_queue = { path = "components/message_queue" }
zstd = { version = "0.12", default-features = false }

[dependencies]
analytic_engine = { workspace = true }
catalog = { workspace = true }
catalog_impls = { workspace = true }
clap = { workspace = true }
cluster = { workspace = true }
common_util = { workspace = true }
df_operator = { workspace = true }
etcd-client = { workspace = true }
interpreters = { workspace = true }
log = { workspace = true }
logger = { workspace = true }
meta_client = { workspace = true }
moka = { version = "0.10", features = ["future"] }
proxy = { workspace = true }
query_engine = { workspace = true }
router = { workspace = true }
serde = { workspace = true }
server = { workspace = true }
signal-hook = "0.3"
table_engine = { workspace = true }
toml = { workspace = true }
tracing_util = { workspace = true }

[build-dependencies]
vergen = { version = "7", default-features = false, features = ["build", "git", "rustc"] }

# This profile optimizes for good runtime performance.
[profile.release]
# reference: https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1
debug = true
overflow-checks = true

# This profile is used to produce a smaller (no symbols) binary with a little bit poorer performance,
# but with a faster speed and low memory consumption required by compiling.
[profile.release-slim]
inherits = "release"
codegen-units = 16
debug = false
strip = true
